name: Windows CI/CD

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"
  workflow_dispatch:

concurrency:
  group: windows-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows:
    if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
    permissions:
      contents: read
    uses: pgextwin/build/.github/workflows/build-extension.yml@c788ca7ab8210472b12af9e6a1de5e1a4f286212
    with:
      extension_config_path: config/extension.json

  release_build:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    permissions:
      contents: read
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: pgextwin/build/.github/workflows/build-extension-attested.yml@c788ca7ab8210472b12af9e6a1de5e1a4f286212
    with:
      extension_config_path: config/extension.json

  release:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    needs: release_build
    permissions:
      contents: write
    uses: pgextwin/build/.github/workflows/release-extension.yml@c788ca7ab8210472b12af9e6a1de5e1a4f286212
    with:
      extension_name: ${{ needs.release_build.outputs.extension_name }}
      upstream_repository: ${{ needs.release_build.outputs.upstream_repository }}
