name: Windows CI/CD

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"
  workflow_dispatch:

concurrency:
  group: windows-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows:
    permissions:
      contents: read
    uses: pgextwin/build/.github/workflows/build-extension.yml@d002b6cd38325de18f4016f50ef7bce7f65b8e57
    with:
      extension_config_path: config/extension.json

  release:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    needs: windows
    permissions:
      contents: write
    uses: pgextwin/build/.github/workflows/release-extension.yml@d002b6cd38325de18f4016f50ef7bce7f65b8e57
    with:
      extension_name: ${{ needs.windows.outputs.extension_name }}
      upstream_repository: ${{ needs.windows.outputs.upstream_repository }}
